---
- hosts: all
  become: true
  roles:
  - role: osprep

- hosts: controllers
  become: true
  tasks:
    - name: Install bridge-utils and vlan packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - bridge-utils
        - vlan
      when: ansible_os_family == 'Debian'

    - name: Create Bridges on Controllers
      copy:
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              ens160:
                dhcp4: no
            vlans:
              vlan1000:
                id: 1000
                link: ens160
                dhcp4: no
              vlan1002:
                id: 1002
                link: ens160
                dhcp4: no
              vlan1004:
                id: 1004
                link: ens160
                dhcp4: no
            bridges:
              br-mgmt:
                interfaces:
                  - vlan1000
                dhcp4: no
                addresses:
                  - {{ br_mgmt_ip }}
                gateway4: 172.16.100.254
              br-vxlan:
                interfaces:
                  - vlan1002
                dhcp4: no
                addresses:
                  - {{ br_vxlan_ip }}
                gateway4: 172.16.120.254
              br-storage:
                interfaces:
                  - vlan1004
                dhcp4: no
                addresses:
                  - {{ br_storage_ip }}
                gateway4: 172.16.150.254
        dest: /etc/netplan/01-vlan-bridge.yaml
    
    - name: remove default netplan
      file:
        path: /etc/netplan/00-installer-config.yaml
        state: absent
    - name: apply netplan
      command: netplan apply
      async: 45
      



- name: Create Networking on compute hosts
  hosts: compute  # Replace with the target host or groudp of hosts
  become: yes  # Run tasks with elevated privileges

  tasks:

    - name: Create Bridges on Compute nodes
      copy:
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              ens160:
                dhcp4: no
            vlans:
              vlan1000:
                id: 1000
                link: ens160
                dhcp4: no
              vlan1002:
                id: 1002
                link: ens160
                dhcp4: no
              vlan1004:
                id: 1004
                link: ens160
                dhcp4: no
            bridges:
              br-mgmt:
                interfaces:
                  - vlan1000
                dhcp4: no
                addresses:
                  - {{ br_mgmt_ip }}
                gateway4: 172.16.100.254
              br-vxlan:
                interfaces:
                  - vlan1002
                dhcp4: no
                addresses:
                  - {{ br_vxlan_ip }}
                gateway4: 172.16.120.254
              br-storage:
                interfaces:
                  - vlan1004
                dhcp4: no
                addresses:
                  - {{ br_storage_ip }}
                gateway4: 172.16.150.254
        dest: /etc/netplan/01-vlan-bridge.yaml
    
    - name: remove default netplan
      file:
        path: /etc/netplan/00-installer-config.yaml
        state: absent
    - name: apply netplan
      command: netplan apply
      async: 45

- name: Create Networking on storage hosts
  hosts: storage  # Replace with the target host or group of hosts
  become: yes  # Run tasks with elevated privileges

  tasks:
    - name: Create Bridges on Storage Nodes
      copy:
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              ens160:
                dhcp4: no
            vlans:
              vlan1000:
                id: 1000
                link: ens160
                dhcp4: no
              vlan1004:
                id: 1004
                link: ens160
                dhcp4: no
            bridges:
              br-mgmt:
                interfaces:
                  - vlan1000
                dhcp4: no
                addresses:
                  - {{ br_mgmt_ip }}
                gateway4: 172.16.100.254
              br-storage:
                interfaces:
                  - vlan1004
                dhcp4: no
                addresses:
                  - {{ br_storage_ip }}
                gateway4: 172.16.150.254
        dest: /etc/netplan/01-vlan-bridge.yaml
    
    - name: remove default netplan
      file:
        path: /etc/netplan/00-installer-config.yaml
        state: absent   
    - name: apply netplan
      command: netplan apply
      async: 45

- name: Create Networking on HAPROXY hosts
  hosts: haproxy  # Replace with the target host or group of hosts
  become: yes  # Run tasks with elevated privileges

  tasks:
    - name: Create Bridges on HAPROXY
      copy:
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              ens160:
                dhcp4: no
            vlans:
              vlan1001:
                id: 1001
                link: ens160
                dhcp4: no
              vlan1000:
                id: 1000
                link: ens160
                dhcp4: no
            bridges:
              br-mgmt:
                interfaces:
                  - vlan1000
                dhcp4: no
                addresses:
                  - {{ br_mgmt_ip }}
                gateway4: 172.16.100.254
              br-public:
                interfaces:
                  - vlan1001
                dhcp4: no
                addresses:
                  - {{ br_public_ip }}
                gateway4: 172.16.10.254
        dest: /etc/netplan/01-vlan-bridge.yaml

    - name: remove default netplan
      file:
        path: /etc/netplan/00-installer-config.yaml
        state: absent
    - name: apply netplan
      command: netplan apply
      async: 45

